/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/96WFagKU1UG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export default function Presentation() {
  return (
    (<section className="bg-gray-950 py-20 px-4 md:px-6 lg:py-32">
      <div className="container mx-auto max-w-6xl">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-8">
          <div
            className="relative group overflow-hidden rounded-lg shadow-lg transition-transform duration-500 ease-in-out hover:-translate-y-2">
            <div
              className="absolute inset-0 bg-gradient-to-r from-[#6366F1] to-[#EC4899] opacity-50 blur-xl" />
            <div className="relative z-10 p-6 md:p-8 flex flex-col justify-end h-full">
              <h3 className="text-2xl md:text-3xl font-bold text-white mb-2">IA generated</h3>
              <p className="text-gray-300 mb-4">Explore a dynamic, ever-changing world of platforms and obstacles.</p>
              <div className="flex items-center gap-2">
                <GamepadIcon className="w-6 h-6 text-white" />
                <span className="text-gray-300 text-sm">RAG-generated</span>
              </div>
            </div>
          </div>
          <div
            className="relative group overflow-hidden rounded-lg shadow-lg transition-transform duration-500 ease-in-out hover:-translate-y-2">
            <div
              className="absolute inset-0 bg-gradient-to-r from-[#10B981] to-[#F59E0B] opacity-50 blur-xl" />
            <div className="relative z-10 p-6 md:p-8 flex flex-col justify-end h-full">
              <h3 className="text-2xl md:text-3xl font-bold text-white mb-2">Endless generation</h3>
              <p className="text-gray-300 mb-4">Dodge obstacles and blast your way through a never-ending onslaught.</p>
              <div className="flex items-center gap-2">
                <GamepadIcon className="w-6 h-6 text-white" />
                <span className="text-gray-300 text-sm">RAG-generated</span>
              </div>
            </div>
          </div>
          <div
            className="relative group overflow-hidden rounded-lg shadow-lg transition-transform duration-500 ease-in-out hover:-translate-y-2">
            <div
              className="absolute inset-0 bg-gradient-to-r from-[#9333EA] to-[#DB2777] opacity-50 blur-xl" />
            <div className="relative z-10 p-6 md:p-8 flex flex-col justify-end h-full">
              <h3 className="text-2xl md:text-3xl font-bold text-white mb-2">Imaginary</h3>
              <p className="text-gray-300 mb-4">Explore a mysterious world, filled with dangers and treasures.</p>
              <div className="flex items-center gap-2">
                <GamepadIcon className="w-6 h-6 text-white" />
                <span className="text-gray-300 text-sm">RAG-generated</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>)
  );
}

function GamepadIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="6" x2="10" y1="12" y2="12" />
      <line x1="8" x2="8" y1="10" y2="14" />
      <line x1="15" x2="15.01" y1="13" y2="13" />
      <line x1="18" x2="18.01" y1="11" y2="11" />
      <rect width="20" height="12" x="2" y="6" rx="2" />
    </svg>)
  );
}
